// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWqlooDQNqiG3o4PqGW54oeFJ73gaEMU',
    appId: '1:504528313499:web:a001ec9d60867be53c7a3e',
    messagingSenderId: '504528313499',
    projectId: 'todoapp-7358b',
    authDomain: 'todoapp-7358b.firebaseapp.com',
    storageBucket: 'todoapp-7358b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF2u6R1Cs5rpLmB_hpXmFhY4WGUHGIpEM',
    appId: '1:504528313499:android:60d692bee8a134333c7a3e',
    messagingSenderId: '504528313499',
    projectId: 'todoapp-7358b',
    storageBucket: 'todoapp-7358b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVaEalKaRNXcXz09TECFdZw7PTHZdCqEc',
    appId: '1:504528313499:ios:a1bf8e85848009603c7a3e',
    messagingSenderId: '504528313499',
    projectId: 'todoapp-7358b',
    storageBucket: 'todoapp-7358b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVaEalKaRNXcXz09TECFdZw7PTHZdCqEc',
    appId: '1:504528313499:ios:8be2f91bb94505813c7a3e',
    messagingSenderId: '504528313499',
    projectId: 'todoapp-7358b',
    storageBucket: 'todoapp-7358b.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
